[tool.poetry]
name = "wagtail-channels"
version = "0.1.0"
description = ""
authors = ["Michael Hearn <git@mikehearn.net>"]

[tool.poetry.dependencies]
python = "^3.7"
channels = "^2.1"

[build-system]
requires = ["poetry>=0.12", "setuptools", "wheel"]
build-backend = "poetry.masonry.api"
